"""
### Generated by CLAUDE ###

One-time BigQuery extraction (chamado + geo) to data/raw/*.parquet.

Uses the `basedosdados` library (`read_sql`) to run the queries against the
public `datario` project on BigQuery, billed to the project passed via
--billing-project.

Auth:
(basedosdados, from_file=False): authenticates via pydata-google-auth.

Usage:
    python pipeline/scripts/extract_bigquery.py --billing-project <PROJECT_ID>
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path

import basedosdados as bd

DOWNLOAD_PLAN: list[tuple[str, str, str]] = [
    ("dados_mestres", "regiao_administrativa", "regiao_administrativa.parquet"),
    ("dados_mestres", "area_planejamento", "area_planejamento.parquet"),
    ("dados_mestres", "subprefeitura", "subprefeitura.parquet"),
    ("dados_mestres", "bairro", "bairro.parquet"),
    ("adm_central_atendimento_1746", "chamado", "chamado.parquet"),
]

QUERY_CHAMADO = """
SELECT
    id_chamado,
    data_inicio,
    data_fim,
    data_alvo_finalizacao AS prazo_atendimento,
    tipo,
    subtipo,
    status,
    situacao,
    id_bairro,
    categoria,
    tipo_situacao,
    nome_unidade_organizacional,
    reclamacoes,
    longitude,
    latitude,
    data_particao
FROM `datario.adm_central_atendimento_1746.chamado`
WHERE data_particao >= '2023-01-01'
"""

QUERY_BAIRRO = """
SELECT
    id_bairro,
    nome,
    subprefeitura,
    nome_regiao_administrativa,
    nome_regiao_planejamento,
    geometry_wkt
FROM `datario.dados_mestres.bairro`
"""

QUERY_REGIAO_ADMINISTRATIVA = """
SELECT
    id_regiao_administrativa,
    nome,
    id_area_planejamento_sms
FROM `datario.dados_mestres.regiao_administrativa`
"""

QUERY_AREA_PLANEJAMENTO = """
SELECT
    id_area_planejamento,
    id_area_planejamento_numerico,
    geometry_wkt
FROM `datario.dados_mestres.area_planejamento`
"""

QUERY_SUBPREFEITURA = """
SELECT
    subprefeitura,
    area,
    perimetro,
    geometry_wkt
FROM `datario.dados_mestres.subprefeitura`
"""

EXTRACTION_QUERIES: dict[tuple[str, str], str] = {
    ("adm_central_atendimento_1746", "chamado"): QUERY_CHAMADO,
    ("dados_mestres", "bairro"): QUERY_BAIRRO,
    ("dados_mestres", "regiao_administrativa"): QUERY_REGIAO_ADMINISTRATIVA,
    ("dados_mestres", "area_planejamento"): QUERY_AREA_PLANEJAMENTO,
    ("dados_mestres", "subprefeitura"): QUERY_SUBPREFEITURA,
}


def setup_logging(log_path: Path) -> logging.Logger:
    """Configure a console + file logger for the extraction run.

    Args:
        log_path: File the logs are written to; parent dirs are created.

    Returns:
        A logger named ``extract_bigquery`` at ``INFO`` level, with handlers
        for stdout and ``log_path``.
    """
    logger = logging.getLogger("extract_bigquery")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    fmt = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    console = logging.StreamHandler(sys.stdout)
    console.setFormatter(fmt)
    logger.addHandler(console)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setFormatter(fmt)
    logger.addHandler(file_handler)
    return logger


def _format_duration(seconds: float) -> str:
    """Render an elapsed time as a compact human-readable string.

    Args:
        seconds: Elapsed time in seconds.

    Returns:
        A string such as ``"12.3s"``, ``"1m 5s"`` or ``"2h 3m 4s"``.
    """
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes, secs = divmod(int(seconds), 60)
    if minutes < 60:
        return f"{minutes}m {secs}s"
    hours, minutes = divmod(minutes, 60)
    return f"{hours}h {minutes}m {secs}s"


def extraction_query(dataset_id: str, table_name: str) -> str:
    """Look up the SQL that extracts a given ``datario`` table.

    Args:
        dataset_id: BigQuery dataset, e.g. ``"dados_mestres"``.
        table_name: Table within the dataset, e.g. ``"bairro"``.

    Returns:
        The SQL string registered for the table in ``EXTRACTION_QUERIES``.

    Raises:
        ValueError: If no query is registered for ``dataset_id.table_name``.
    """
    key = (dataset_id, table_name)
    if key not in EXTRACTION_QUERIES:
        known = ", ".join(f"{d}.{t}" for d, t in sorted(EXTRACTION_QUERIES))
        raise ValueError(f"Unknown table {dataset_id}.{table_name}. Known: {known}")
    return EXTRACTION_QUERIES[key]


def download_query_to_parquet(
    query: str,
    billing_project: str,
    output: Path,
    *,
    logger: logging.Logger,
    label: str,
) -> int:
    """Run a query via basedosdados and write the result to a Parquet file.

    Args:
        query: SQL to execute against BigQuery.
        billing_project: GCP project billed for the query.
        output: Destination path; a ``.parquet`` suffix is enforced and an
            existing file is overwritten.
        logger: Logger for progress messages.
        label: Human-readable table label used in log lines.

    Returns:
        The number of rows written to ``output``.
    """
    if output.suffix != ".parquet":
        output = output.with_suffix(".parquet")

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        logger.warning("%s: sobrescrevendo arquivo existente (%s)", label, output)

    logger.info(
        "%s: enviando query ao BigQuery via basedosdados (cobrança no projeto %s)",
        label,
        billing_project,
    )

    t0 = time.monotonic()
    df = bd.read_sql(query, billing_project_id=billing_project)
    total = len(df)
    logger.info(
        "%s: query concluída em %s | %s linhas carregadas em memória",
        label,
        _format_duration(time.monotonic() - t0),
        f"{total:,}",
    )

    logger.info("%s: gravando Parquet → %s", label, output)
    df.to_parquet(output, compression="snappy", index=False)

    logger.info(
        "%s: concluído — %s linhas, arquivo %s, tempo total %s",
        label,
        f"{total:,}",
        output.name,
        _format_duration(time.monotonic() - t0),
    )
    return total


def download_table(
    dataset_id: str,
    table_name: str,
    output: Path,
    billing_project: str,
    logger: logging.Logger,
) -> int:
    """Resolve the query for a table and download it to Parquet.

    Args:
        dataset_id: BigQuery dataset.
        table_name: Table within the dataset.
        output: Destination Parquet path.
        billing_project: GCP project billed for the query.
        logger: Logger for progress messages.

    Returns:
        The number of rows written to ``output``.

    Raises:
        ValueError: If the table has no registered query.
    """
    label = f"datario.{dataset_id}.{table_name}"
    query = extraction_query(dataset_id, table_name)
    return download_query_to_parquet(
        query,
        billing_project,
        output,
        logger=logger,
        label=label,
    )


def download_all_tables(
    billing_project: str,
    raw_dir: Path,
    logger: logging.Logger,
) -> None:
    """Download every table in ``DOWNLOAD_PLAN`` to ``raw_dir`` as Parquet.

    Tables whose target Parquet file already exists in ``raw_dir`` are skipped
    (no query is sent to BigQuery), so re-runs are cheap and idempotent. Delete
    the file to force a fresh download.

    Args:
        billing_project: GCP project billed for the queries.
        raw_dir: Output directory for the ``*.parquet`` files.
        logger: Logger for progress messages.

    Raises:
        Exception: Re-raises any per-table failure after logging it.
    """
    total_steps = len(DOWNLOAD_PLAN)
    run_started = time.monotonic()
    logger.info(
        "Início do download (%d tabelas) → %s",
        total_steps,
        raw_dir.resolve(),
    )

    for step, (dataset_id, table_name, filename) in enumerate(DOWNLOAD_PLAN, start=1):
        out = raw_dir / filename
        logger.info("=" * 72)
        logger.info("[%d/%d] %s", step, total_steps, f"datario.{dataset_id}.{table_name}")
        logger.info("Destino: %s", out.resolve())
        if out.exists():
            logger.info(
                "[%d/%d] Já existe — pulando download",
                step,
                total_steps,
            )
            continue
        step_started = time.monotonic()
        try:
            rows = download_table(dataset_id, table_name, out, billing_project, logger)
        except Exception:
            logger.exception(
                "[%d/%d] Falha em %s após %s",
                step,
                total_steps,
                f"datario.{dataset_id}.{table_name}",
                _format_duration(time.monotonic() - step_started),
            )
            raise
        logger.info(
            "[%d/%d] OK — %s linhas em %s",
            step,
            total_steps,
            f"{rows:,}",
            _format_duration(time.monotonic() - step_started),
        )

    logger.info("=" * 72)
    logger.info(
        "Download finalizado em %s. Próximo passo: cd pipeline && dbt run",
        _format_duration(time.monotonic() - run_started),
    )


def main() -> None:
    """Parse ``--billing-project`` and extract all tables to ``data/raw``."""
    raw_dir = Path(__file__).resolve().parents[2] / "data" / "raw"

    parser = argparse.ArgumentParser(
        description="Export chamado + dados_mestres from datario to data/raw/*.parquet",
    )
    parser.add_argument(
        "--billing-project",
        required=True,
        help="GCP project billed for BigQuery queries",
    )
    args = parser.parse_args()

    raw_dir.mkdir(parents=True, exist_ok=True)
    log_path = raw_dir / "extract_bigquery.log"
    logger = setup_logging(log_path)
    logger.info("Log também em %s", log_path.resolve())
    logger.info("Projeto de cobrança: %s", args.billing_project)
    logger.info("Diretório de saída: %s", raw_dir.resolve())

    download_all_tables(args.billing_project, raw_dir, logger)


if __name__ == "__main__":
    main()
